### ISSUE TITLE
使用Gallery Post报错

### ISSUE THREAD

**Issue by ciweigg2** [amehime/hexo-theme-shoka#2]
md文件内容：

title: Gallery Post
date: 2013-12-25 00:16:18
photos:
- assets/wallpaper-2572384.jpg
- assets/wallpaper-2311325.jpg
- assets/wallpaper-878514.jpg
- http://placehold.it/350x150.jpg
---

报错内容：

ERROR Template render error: (/Volumes/uzi/博客/blog-source/themes/shoka/layout/post.njk)
  Template render error: (/Volumes/uzi/博客/blog-source/themes/shoka/layout/post.njk)
  Template render error: (/Volumes/uzi/博客/blog-source/themes/shoka/layout/post.njk)
  Template render error: (/Volumes/uzi/博客/blog-source/themes/shoka/layout/post.njk)
  Template render error: (/Volumes/uzi/博客/blog-source/themes/shoka/layout/post.njk) [Line 10, Column 98]
  Template render error: (/Volumes/uzi/博客/blog-source/themes/shoka/layout/post.njk) [Line 48, Column 29]
  Template render error: (/Volumes/uzi/博客/blog-source/themes/shoka/layout/post.njk)
  Template render error: (/Volumes/uzi/博客/blog-source/themes/shoka/layout/post.njk)
  Template render error: (/Volumes/uzi/博客/blog-source/themes/shoka/layout/post.njk) [Line 7, Column 3]
  Template render error: (/Volumes/uzi/博客/blog-source/themes/shoka/layout/post.njk) [Line 31, Column 19]
  TypeError: Cannot destructure property 'config' of 'this' as it is undefined.
    at Object._prettifyError (/Volumes/uzi/博客/blog-source/node_modules/nunjucks/src/lib.js:36:11)
    at /Volumes/uzi/博客/blog-source/node_modules/nunjucks/src/environment.js:561:19
    at Template.root [as rootRenderFunc] (eval at _compile (/Volumes/uzi/博客/blog-source/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:61:3)
    at Template.render (/Volumes/uzi/博客/blog-source/node_modules/nunjucks/src/environment.js:550:10)
    at /Volumes/uzi/博客/blog-source/themes/shoka/scripts/renderer/njk.js:41:29
    at _View._compiled (/Volumes/uzi/博客/blog-source/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/Volumes/uzi/博客/blog-source/node_modules/hexo/lib/theme/view.js:39:17)
    at /Volumes/uzi/博客/blog-source/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/Volumes/uzi/博客/blog-source/node_modules/bluebird/js/release/util.js:16:23)
    at /Volumes/uzi/博客/blog-source/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Volumes/uzi/博客/blog-source/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:467:10)
    at resume_ (_stream_readable.js:981:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
ERROR Template render error: (/Volumes/uzi/博客/blog-source/themes/shoka/layout/index.njk)
  Template render error: (/Volumes/uzi/博客/blog-source/themes/shoka/layout/index.njk)
  Template render error: (/Volumes/uzi/博客/blog-source/themes/shoka/layout/index.njk)
  Template render error: (/Volumes/uzi/博客/blog-source/themes/shoka/layout/index.njk) [Line 7, Column 56]
  Template render error: (/Volumes/uzi/博客/blog-source/themes/shoka/layout/index.njk) [Line 48, Column 29]
  Template render error: (/Volumes/uzi/博客/blog-source/themes/shoka/layout/index.njk)
  Template render error: (/Volumes/uzi/博客/blog-source/themes/shoka/layout/index.njk)
  Template render error: (/Volumes/uzi/博客/blog-source/themes/shoka/layout/index.njk) [Line 8, Column 12]
  Template render error: (/Volumes/uzi/博客/blog-source/themes/shoka/layout/index.njk) [Line 34, Column 13]
  Template render error: (/Volumes/uzi/博客/blog-source/themes/shoka/layout/index.njk) [Line 35, Column 25]
  TypeError: Cannot destructure property 'config' of 'this' as it is undefined.
    at Object._prettifyError (/Volumes/uzi/博客/blog-source/node_modules/nunjucks/src/lib.js:36:11)
    at /Volumes/uzi/博客/blog-source/node_modules/nunjucks/src/environment.js:561:19
    at Template.root [as rootRenderFunc] (eval at _compile (/Volumes/uzi/博客/blog-source/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:43:3)
    at Template.render (/Volumes/uzi/博客/blog-source/node_modules/nunjucks/src/environment.js:550:10)
    at /Volumes/uzi/博客/blog-source/themes/shoka/scripts/renderer/njk.js:41:29
    at _View._compiled (/Volumes/uzi/博客/blog-source/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/Volumes/uzi/博客/blog-source/node_modules/hexo/lib/theme/view.js:39:17)
    at /Volumes/uzi/博客/blog-source/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/Volumes/uzi/博客/blog-source/node_modules/bluebird/js/release/util.js:16:23)
    at /Volumes/uzi/博客/blog-source/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Volumes/uzi/博客/blog-source/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:467:10)
    at resume_ (_stream_readable.js:981:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by amehime** [comment]
这个bug之前已经修复啦，请下载最新版文件覆盖哦

**Comment by ciweigg2** [comment]
Gallery Post不支持写url地址 本地测试会出现这样的拼接http://localhost:4000/http:/placehold.it/350x150.jpg

**Comment by amehime** [comment]
bug2号已修复，感谢反馈！
