### ISSUE TITLE
打开时报错

### ISSUE THREAD

**Issue by g1062547668** [amehime/hexo-theme-shoka#22]
$ hexo s
INFO  Validating config
ERROR {
  err: Error: Cannot find module 'pangu'
  Require stack:
  - C:\Users\Administrator\Desktop\the\the\themes\Shoka\scripts\renderer\njk.js
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
      at Function.Module._load (internal/modules/cjs/loader.js:725:27)
      at Module.require (internal/modules/cjs/loader.js:952:19)
      at req (C:\Users\Administrator\Desktop\the\the\node_modules\hexo\lib\hexo\index.js:292:23)
      at C:\Users\Administrator\Desktop\the\the\themes\Shoka\scripts\renderer\njk.js:6:15
      at C:\Users\Administrator\Desktop\the\the\node_modules\hexo\lib\hexo\index.js:305:14
      at tryCatcher (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:461:21) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      'C:\\Users\\Administrator\\Desktop\\the\\the\\themes\\Shoka\\scripts\\renderer\\njk.js'
    ]
  }
} Script load failed: %s themes\Shoka\scripts\renderer\njk.js
INFO  Start processing
FATAL {
  err: Error: Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default.
      at Object.safeLoad (C:\Users\Administrator\Desktop\the\the\node_modules\js-yaml\index.js:10:11)
      at Hexo.<anonymous> (C:\Users\Administrator\Desktop\the\the\themes\Shoka\scripts\generaters\config.js:41:41)
      at Hexo.tryCatcher (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\util.js:16:23)
      at Hexo.<anonymous> (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\method.js:15:34)
      at C:\Users\Administrator\Desktop\the\the\node_modules\hexo\lib\extend\filter.js:67:52
      at tryCatcher (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\util.js:16:23)
      at Object.gotValue (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\reduce.js:166:18)
      at Object.gotAccum (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\reduce.js:155:25)
      at Object.tryCatcher (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\promise.js:729:18)
      at Promise._fulfill (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\promise.js:673:18)
      at Promise._resolveCallback (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\promise.js:466:57)
      at Promise._settlePromiseFromHandler (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\promise.js:559:17)
      at Promise._settlePromise (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\promise.js:729:18)
      at Promise._fulfill (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\promise.js:673:18)
      at PromiseArray._resolve (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\promise_array.js:127:19)
      at PromiseArray._promiseFulfilled (C:\Users\Administrator\Desktop\the\the\node_modules\bluebird\js\release\promise_array.js:145:14)
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html

**Comment by zztqsh** [comment]
npm install pangu @g1062547668

**Comment by monkey-HH** [comment]
npm install remark-pangu

**Comment by Liuhang0624** [comment]
> npm install remark-pangu

我的为什么安装完了还是不行啊

**Comment by THEO1126** [comment]
谢谢你的邮件，我已经收到啦！


    


    
        我去当喜之郎了，回来带太空人给你！
    


    
        
    


    
        想要立即召唤我？
    


    
        试试

    
        
            电脑点点我
        
    


    
        发送“呼啦呼啦”变身小魔仙吧！
