### ISSUE TITLE
报错：Unhandled rejection Template render error

### ISSUE THREAD

**Issue by zztqsh** [amehime/hexo-theme-shoka#23]
这个要怎么解决？

$ hexo s
INFO  Validating config
INFO  Start processing
Prism's Diff Highlight plugin requires the Diff language definition (prism-diff.js).Make sure the language definition is loaded or use Prism's Autoloader plugin.
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
Unhandled rejection Template render error: (D:\Programming\blog\THEO\Hexo\themes\shoka\layout\index.njk)
  Template render error: (D:\Programming\blog\THEO\Hexo\themes\shoka\layout\index.njk)
  Template render error: (D:\Programming\blog\THEO\Hexo\themes\shoka\layout\index.njk) [Line 10, Column 98]
  Template render error: (D:\Programming\blog\THEO\Hexo\themes\shoka\layout\index.njk) [Line 7, Column 61]
  Template render error: (D:\Programming\blog\THEO\Hexo\themes\shoka\layout\index.njk) [Line 49, Column 29]
  Template render error: (D:\Programming\blog\THEO\Hexo\themes\shoka\layout\index.njk)
  Template render error: (D:\Programming\blog\THEO\Hexo\themes\shoka\layout\index.njk)
  Template render error: (D:\Programming\blog\THEO\Hexo\themes\shoka\layout\index.njk)
  Template render error: (D:\Programming\blog\THEO\Hexo\themes\shoka\layout\index.njk) [Line 9, Column 12]
  Template render error: (D:\Programming\blog\THEO\Hexo\themes\shoka\layout\index.njk) [Line 35, Column 13]
  Template render error: (D:\Programming\blog\THEO\Hexo\themes\shoka\layout\index.njk) [Line 35, Column 25]
  TypeError: img.startsWith is not a function
    at Object._prettifyError (D:\Programming\blog\THEO\Hexo\node_modules\nunjucks\src\lib.js:36:11)
    at D:\Programming\blog\THEO\Hexo\node_modules\nunjucks\src\environment.js:563:19
    at Template.root [as rootRenderFunc] (eval at _compile (D:\Programming\blog\THEO\Hexo\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:45:3)
    at Template.render (D:\Programming\blog\THEO\Hexo\node_modules\nunjucks\src\environment.js:552:10)
    at D:\Programming\blog\THEO\Hexo\themes\shoka\scripts\renderer\njk.js:44:29
    at _View._compiled (D:\Programming\blog\THEO\Hexo\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\Programming\blog\THEO\Hexo\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\Programming\blog\THEO\Hexo\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\Programming\blog\THEO\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at D:\Programming\blog\THEO\Hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\Programming\blog\THEO\Hexo\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:481:10)
    at resume_ (internal/streams/readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by CathLee** [comment]
呜呜您解决了吗？我的也报这个错，不知道是配置哪出来问题

**Comment by CathLee** [comment]
已解决，把package.json和博主姐姐的设置成一样就好了

**Comment by THEO1126** [comment]
谢谢你的邮件，我已经收到啦！


    


    
        我去当喜之郎了，回来带太空人给你！
    


    
        
    


    
        想要立即召唤我？
    


    
        试试

    
        
            电脑点点我
        
    


    
        发送“呼啦呼啦”变身小魔仙吧！

**Comment by dabing85** [comment]
可以看看你们改成啥样了吗，我也报这样的错误

**Comment by THEO1126** [comment]
谢谢您的邮件，俺已经收到啦！


    


    
        我去当喜之郎了，回来带太空人给你！
快发送“呼啦呼啦”变身小魔仙吧！
