### ISSUE TITLE
hexo  g  报错

### ISSUE THREAD

**Issue by luckyzluz** [amehime/hexo-theme-shoka#24]
INFO  Validating config
FATAL YAMLException: bad indentation of a mapping entry (73:11)

 70 | # bgm
 71 | audio:
 72 |    - title: 列表1
 73 |       list:
----------------^
 74 |         - https://music.163.com/#/playlis ...
 75 |         - https://music.163.com/#/playlis ...
    at generateError (C:\studyexe\WWW\myblog\node_modules\js-yaml\lib\loader.js:183:10)
    at throwError (C:\studyexe\WWW\myblog\node_modules\js-yaml\lib\loader.js:187:9)
    at readBlockMapping (C:\studyexe\WWW\myblog\node_modules\js-yaml\lib\loader.js:1182:7)
    at composeNode (C:\studyexe\WWW\myblog\node_modules\js-yaml\lib\loader.js:1441:12)
    at readBlockSequence (C:\studyexe\WWW\myblog\node_modules\js-yaml\lib\loader.js:1008:5)
    at composeNode (C:\studyexe\WWW\myblog\node_modules\js-yaml\lib\loader.js:1440:12)
    at readBlockMapping (C:\studyexe\WWW\myblog\node_modules\js-yaml\lib\loader.js:1164:11)
    at composeNode (C:\studyexe\WWW\myblog\node_modules\js-yaml\lib\loader.js:1441:12)
    at readDocument (C:\studyexe\WWW\myblog\node_modules\js-yaml\lib\loader.js:1625:3)
    at loadDocuments (C:\studyexe\WWW\myblog\node_modules\js-yaml\lib\loader.js:1688:5)
    at Object.load (C:\studyexe\WWW\myblog\node_modules\js-yaml\lib\loader.js:1714:19)
    at Hexo.yamlHelper (C:\studyexe\WWW\myblog\node_modules\hexo\lib\plugins\renderer\yaml.js:7:15)
    at Hexo.tryCatcher (C:\studyexe\WWW\myblog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\studyexe\WWW\myblog\node_modules\bluebird\js\release\method.js:15:34)
    at C:\studyexe\WWW\myblog\node_modules\hexo\lib\hexo\render.js:75:22
    at tryCatcher (C:\studyexe\WWW\myblog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\studyexe\WWW\myblog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\studyexe\WWW\myblog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\studyexe\WWW\myblog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\studyexe\WWW\myblog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\studyexe\WWW\myblog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\studyexe\WWW\myblog\node_modules\bluebird\js\release\async.js:86:9) {
  reason: 'bad indentation of a mapping entry',
  mark: {
    name: null,
    buffer: 'alternate: Yume Shoka\n' +
      '\n' +
      '# Assets\n' +
      'statics: / #//cdn.jsdelivr.net/gh/amehime/shoka@latest/\n' +
      '\n' +
      'open_graph:\n' +
      '  #twitter_id:\n' +
      '  #google_plus:\n' +
      '  #fb_admins:\n' +
      '  #fb_app_id:\n' +
      '\n' +
      'menu:\n' +
      '  home: / || home\n' +
      '  posts:\n' +
      '    default: / || feather\n' +
      '    archives: /archives/ || list-alt\n' +
      '    categories: /categories/ || th\n' +
      '    tags: /tags/ || tags\n' +
      '  friends: /friends/ || heart\n' +
      '\n' +
      '# Social Links\n' +
      '# Usage: `Key: permalink || icon || color`\n' +
      '# Key is the link label showing to end users.\n' +
      '# Value before `||` delimiter is the target permalink,\n' +
      '# secend value is the name of Font icon.\n' +
      'social:\n' +
      '  github: https://github.com/amehime || github || "#191717"\n' +
      '  #google: https://plus.google.com/yourname || google\n' +
      '  twitter: https://twitter.com/amehime || twitter || "#00aff0"\n' +
      '  zhihu: https://www.zhihu.com/people/rurismzk || zhihu || "#1e88e5"\n' +
      '  music: https://music.163.com/#/user/home?id=12886823 || cloud-music || "#e60026"\n' +
      '  weibo: https://weibo.com/amehime || weibo || "#ea716e"\n' +
      '  about: https://about.me/amehime || address-card || "#3b5998"\n' +
      '  #email: mailto:yourname@mail.com || envelope || "#55acd5"\n' +
      '  #facebook: https://www.facebook.com/yourname || facebook\n' +
      '  #stackoverflow: https://stackoverflow.com/yourname || stack-overflow\n' +
      '  #youtube: https://youtube.com/yourname || youtube\n' +
      '  #instagram: https://instagram.com/yourname || instagram\n' +
      '  #skype: skype:yourname?call|chat || skype\n' +
      '  #douban: https://www.douban.com/people/yourname/ || douban\n' +
      '\n' +
      'footer:\n' +
      '  # Specify the date when the site was setup. If not defined, current year will be used.\n' +
      '  since: 2010\n' +
      '  count: true\n' +
      '\n' +
      'post:\n' +
      '  count: true\n' +
      '\n' +
      '\n' +
      '# ---------------------------------------------------------------\n' +
      '# Third Party Plugins & Services Settings\n' +
      '# ---------------------------------------------------------------\n' +
      '\n' +
      '# Comments\n' +
      '# Valine\n' +
      '# For more information: https://valine.js.org, https://github.com/xCss/Valine\n' +
      'valine:\n' +
      '  appId: #这里不要忘了改\n' +
      '  appKey: #这里不要忘了改\n' +
      '  placeholder: ヽ(○´∀`)ﾉ♪ # Comment box placeholder\n' +
      '  pageSize: 10 # Pagination size\n' +
      '  lang: zh-CN\n' +
      '  tagMember:\n' +
      '    master:\n' +
      '      # - deea5a8d259d17182a53be1772e4c182\n' +
      '    friend:\n' +
      '      - deea5a8d259d17182a53be1772e4c182\n' +
      '\n' +
      '# bgm\n' +
      'audio:\n' +
      '   - title: 列表1\n' +
      '      list:\n' +
      '        - https://music.163.com/#/playlist?id=2943811283\n' +
      '        - https://music.163.com/#/playlist?id=2297706586\n' +
      '   - title: 列表2\n' +
      '      list:\n' +
      '        - https://music.163.com/#/playlist?id=2031842656\n' +
      '\n' +
      '# Dependencies: https://github.com/amehime/hexo-renderer-multi-markdown-it\n' +
      'pangu: true\n' +
      '\n' +
      '# ---------------------------------------------------------------\n' +
      '# analytics & SEO Settings\n' +
      '# ---------------------------------------------------------------\n' +
      '\n' +
      '\n' +
      '# Disable Baidu transformation on mobile devices.\n' +
      'disable_baidu_transformation: true\n' +
      '\n' +
      '# Automatically add external URL with Base64 encrypt & decrypt.\n' +
      'exturl: true\n',
    position: 2136,
    line: 72,
    column: 10,
    snippet: ' 70 | # bgm\n' +
      ' 71 | audio:\n' +
      ' 72 |    - title: 列表1\n' +
      ' 73 |       list:\n' +
      '----------------^\n' +
      ' 74 |         - https://music.163.com/#/playlis ...\n' +
      ' 75 |         - https://music.163.com/#/playlis ...'
  }
}

**Comment by luckyzluz** [comment]
百度  是语法  错误什么的 
我这直接覆盖的   原作者配置
   也敲过空格  隔开   依旧报错
可能是位置没找对？

**Comment by Fidelxyz** [comment]
```yml
audio:
  - title: 列表1
    list:
     - https://music.163.com/#/playlist?id=2943811283
     - https://music.163.com/#/playlist?id=2297706586
  - title: 列表2
    list:
    - https://music.163.com/#/playlist?id=2031842656
```

注意 `list` 的缩进
