### ISSUE TITLE
不知道动到哪里，报错了

### ISSUE THREAD

**Issue by hy6xing** [amehime/hexo-theme-shoka#82]
`$ hexo s
INFO  Validating config
INFO  Start processing
ERROR Theme config load failed.
ERROR Process failed: _config.yml
YAMLException: bad indentation of a mapping entry (220:2)

 217 |     investor:
 218 |       # - hash of investor1@emai ...
 219 |
 220 |  bgm
--------^
 221 |  audio:
 222 |    - title: 列表1
    at generateError (E:\我的博客\node_modules\js-yaml\lib\loader.js:183:10)
    at throwError (E:\我的博客\node_modules\js-yaml\lib\loader.js:187:9)
    at readBlockMapping (E:\我的博客\node_modules\js-yaml\lib\loader.js:1182:7)
    at composeNode (E:\我的博客\node_modules\js-yaml\lib\loader.js:1441:12)
    at readDocument (E:\我的博客\node_modules\js-yaml\lib\loader.js:1625:3)
    at loadDocuments (E:\我的博客\node_modules\js-yaml\lib\loader.js:1688:5)
    at Object.load (E:\我的博客\node_modules\js-yaml\lib\loader.js:1714:19)
    at Hexo.yamlHelper (E:\我的博客\node_modules\hexo\lib\plugins\renderer\yaml.js:20:15)
    at Hexo.tryCatcher (E:\我的博客\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (E:\我的博客\node_modules\bluebird\js\release\method.js:15:34)
    at E:\我的博客\node_modules\hexo\lib\hexo\render.js:81:22
    at tryCatcher (E:\我的博客\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\我的博客\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\我的博客\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\我的博客\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\我的博客\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\我的博客\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\我的博客\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\我的博客\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (E:\我的博客\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:475:21)
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Cannot read properties of undefined (reading 'js')
    at Hexo.<anonymous> (E:\我的博客\themes\shoka\scripts\generaters\script.js:24:29)
    at Hexo.tryCatcher (E:\我的博客\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (E:\我的博客\node_modules\bluebird\js\release\method.js:15:34)
    at E:\我的博客\node_modules\hexo\lib\hexo\index.js:407:22
    at tryCatcher (E:\我的博客\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (E:\我的博客\node_modules\bluebird\js\release\map.js:68:38)
    at PromiseArray._iterate (E:\我的博客\node_modules\bluebird\js\release\promise_array.js:115:31)
    at MappingPromiseArray.init (E:\我的博客\node_modules\bluebird\js\release\promise_array.js:79:10)
    at MappingPromiseArray._asyncInit (E:\我的博客\node_modules\bluebird\js\release\map.js:37:10)
    at _drainQueueStep (E:\我的博客\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (E:\我的博客\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\我的博客\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (E:\我的博客\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:475:21)`

能清cl  不能g 能s  推送就更加不能了
217 、218根本就没动过。音乐也直接注释掉也没用，或者是我的注释方法错，告知一下，bgm我全加 #空格.  node-modules也删了重装。

还有就是，原先自带图床挂了，图片都无法显示。我自己又用了picgo建了。但是加到 __images.yml里没有任何效果，怎么改？

**Comment by hy6xing** [comment]
报错已经解决，图床怎么整啊，图片无法显示

**Comment by hy6xing** [comment]
已解决完
